version: "3.8"

x-base: &backend-base
    build: .
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./src:/opt/src

services:
  db:
    container_name: pythondev-db
    env_file:
      - .env.dev
    image: postgres:12.5-alpine
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-django_db}
      POSTGRES_USER: ${POSTGRES_USER:-django_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django_password}
    ports:
      - "5432:5432"
    restart: unless-stopped

  django:
    <<: *backend-base
    command:
    - /bin/bash
    - -c
    - |
      set -e
      while ! nc -z db 5432; do
        sleep 0.1
      done
      echo "Runserver starting"
      python manage.py runserver --insecure 0.0.0.0:8000
      container_name: pythondev-django
      ports:
        - "8000:8000"
      image: pythondev-django
      restart: unless-stopped

  migrate:
    <<: *backend-base
    command:
      - /bin/bash
      - -c
      - |
        set -e
        while ! nc -z db 5432; do
          sleep 0.1
        done
        echo "Running migrations"
        python manage.py makemigrations
        python manage.py migrate
        echo "Loading fixtures"
        python manage.py loaddata core/fixtures/db.json
    container_name: pythondev-migrate
    image: pythondev-migrate
    restart: 'no'
