# Generated by Django 4.2 on 2023-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentry",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
