# Generated by Django 4.2 on 2023-10-07 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_category_user_financialentry_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budgetuser",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetuser",
            name="visitor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="visitor",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budgetuser",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="shared_with_users",
                to="core.budget",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetuser",
            unique_together={("owner", "visitor")},
        ),
        migrations.RemoveField(
            model_name="budgetuser",
            name="user",
        ),
    ]
